### ISSUE TITLE
Question/Help wanted to make sensor for total payments

### ISSUE THREAD

**Issue by GunnarBjoru** [sepodele/home-assistant-sbanken#1]
Hi thank you for making the Sbanken Sensor for HA.
I have tweaked your sensor to make it more useful for me. I have changed from Transactions list to Payments list.
I'm now able to see all upcoming payments in the markdown card. But my wish was to get a total sum for all payment.amount attributes. Any idea how to make such a sensor?
Ideally I would filter all payments until my next salary payment (20th in each month) and sum them to see if I have enough money to pay them ;-) . Any idea would be welcome.

BR Gunnar

**Comment by quack3d** [comment]
It's just a fork. :) . I've added payments to the component now as well. Here's an example to iterate over the payments:

`{% for payment in state_attr('sensor.nameofaccount_21212121212', 'payments') %}
{{- payment.amount }} 
{% endfor %}`

And here's an example to show the sum of those payments:

`{{ state_attr('sensor.nameofaccount_21212121212', 'payments')|map(attribute='amount')|sum }}`
